### ISSUE TITLE
Stile

### ISSUE THREAD

**Issue by fconsiglio98** [DisGabriele/Pokedex#1]
Lo stile potrebbe essere più moderno e uniforme soprattutto: sarebbe meglio applicare lo stile 3D a tutto o a niente; le diverse view potrebbero incastrarsi meglio e lo spazio potrebbe essere gestito meglio, "geometricamente" parlando, così da dare un senso di "ordine". Anche i font potrebbero essere piu moderni. Lo spazio sulla destra della recyclerView potrebbe essere eliminato se non viene usato per la scrollbar.

**Comment by DisGabriele** [comment]
Effettuate modifiche grafiche su nuovo branch
